# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZMR4vTd2hx6RWYhTqLsPg5zsM9IC7rQL
"""

!pip install pycryptodome

from Crypto.Cipher import PKCS1_OAEP
from Crypto.PublicKey import RSA
from binascii import hexlify

private_key = RSA.generate(2048)
public_key = private_key.publickey()
print(type(private_key), type(public_key))

private_pem = private_key.export_key().decode()
public_pem = public_key.export_key().decode()
print(type(private_pem), type(public_pem))
print(private_pem)
print(public_pem)

from Crypto.PublicKey import RSA
from Crypto.Hash import SHA256
from Crypto.Hash import RIPEMD160

SHAhash = SHA256.new(b'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtW5N+HL2mwKOivU/SqDZ+R73YU9gAVrK2eIpnn2HQfFmilJO1s3gGrfvjpQr50sNtfvxvOq8Fw1tBVYQGai6P60CcCtKDacL+5ZUadp7eMzvufXdn3mVJSBY/ys6m98HfcHUBNWtiqZtye0To4w+eXQwAHc2d4WCobfp1MDlp3aGy1N2AxppOSatzMZY4tNepJFawrqM0Qm/9UChkHs+1lTyFNNjEppHdU9eUZSoHtx9zQn+NP058KK0OoVJwayzgF586/wvl7SCKfWlqOkLyILsKP95Rridm86edT0Jk4e3L/qXQnIUYqihLUDKwUpL/m0clbe9Xq5OY396yzJeKQIDAQAB')
print(SHAhash.hexdigest())

Rhash = RIPEMD160.new(b'22abb15704a885ccf7ce201fd1e18633366fafea707fd466c3c1bac28d0924f4')
print('00' + Rhash.hexdigest())

SHA1 = SHA256.new(b'0076d5788c4744d566ffb42708d5c162a12d7f0a20')
SHA1.hexdigest()

SHA2 = SHA256.new(b'54a7549ad423ecc02a834a2fdc1a60211bcb4e82e6dbd97fd4692a6801d0247d')
SHA2.hexdigest()

SHA2.hexdigest()[0:8]

'0076d5788c4744d566ffb42708d5c162a12d7f0a20' + '6976f805'

!pip install base58

import base58 as b58

b58.b58encode('0076d5788c4744d566ffb42708d5c162a12d7f0a206976f805')